name: we_travel
description: "WeTravel is a collaborative travel planner that helps you organize trips, manage itineraries, and share updates and photos with your group... all in one seamless app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.0.5
  google_sign_in: ^6.2.2
  flutter_signin_button: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
