// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBKJs4vNncCHYJPJodQPZOP1vy9Xs2ZU',
    appId: '1:492937032771:web:2cf84fdfa125a99fe690f6',
    messagingSenderId: '492937032771',
    projectId: 'we-travel-database',
    authDomain: 'we-travel-database.firebaseapp.com',
    storageBucket: 'we-travel-database.firebasestorage.app',
    measurementId: 'G-S0ZLEVQEPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0EXlKEdWiIOFY1XyE4J8UjR5Gxi1HRik',
    appId: '1:492937032771:android:038bf390c4149449e690f6',
    messagingSenderId: '492937032771',
    projectId: 'we-travel-database',
    storageBucket: 'we-travel-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8V5cYsBMg1AViZb5acSqQRk7qNzc2aBU',
    appId: '1:492937032771:ios:244cd5bc9cd06f45e690f6',
    messagingSenderId: '492937032771',
    projectId: 'we-travel-database',
    storageBucket: 'we-travel-database.firebasestorage.app',
    iosBundleId: 'com.example.weTravel',
  );
}
